ALTER TABLE  `customer_nurse2c` CHANGE  `chk1`  `chk1` TEXT CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
CHANGE  `chk2`  `chk2` TEXT CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
CHANGE  `chk3`  `chk3` TEXT CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
CHANGE  `chk4`  `chk4` TEXT CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ;


ALTER TABLE  `customer_nurse2c` CHANGE  `chk13`  `chk13` TEXT CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
CHANGE  `chk14`  `chk14` TEXT CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
CHANGE  `chk15`  `chk15` TEXT CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
CHANGE  `chk16`  `chk16` TEXT CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
CHANGE  `chk17`  `chk17` TEXT CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ;